dubbo:
  protocol:
    name: dubbo
    port: 20890
  application:
    name:  dubbo-consumer
  registry:
    id: service-consumer
    address: zookeeper://127.0.0.1:2181
    # 读者请换成自己的zookeeperip
    check: false
  monitor:
    protocol: register
  consumer:
    check:  false
    timeout: 3000

server:
  port: 8062
spring:
  main:
    allow-bean-definition-overriding: true
